In [5]:
import pandas as pd
# Read the CSV file into a DataFrame
df = pd.read_csv('cleaned_dataset.csv')
df.head()
print(df.head())

    Locality  Zip Code Type of Property Subtype of Property      Price  \
0       Gent      9000        Apartment           apartment   229000.0
1      Uccle      1180            House               villa  1250000.0
2  Etterbeek      1040            House               house   875000.0
3  Elversele      9140            House               villa   825000.0
4  Kalmthout      2920            House         manor-house  4750000.0

   Type of Sale  Number of Rooms  Livable Space (m2)  Fully Equipped Kitchen  \
0             1              1.0                  44                       0
1             1              4.0                 584                       1
2             1              4.0                 233                       1
3             1              4.0                 281                       0
4             1              3.0                 326                       0

   Furnished  ...  Terrace  Terrace Area (m2)  Garden  Garden Area (m2)  \
0          0  ...        0                0.0       0               0.0
1          0  ...        0                0.0       1            1085.0
2          0  ...        1               21.0       0               0.0
3          0  ...        0                0.0       0               0.0
4          0  ...        0                0.0       0               0.0

   Swimming Pool  Surface of the Land (m2)  Number of Facades  PEB  \
0              0                       0.0                2.0  5.0
1              0                    1225.0                4.0  0.0
2              0                     112.0                3.0  0.0
3              1                    1450.0                4.0  5.0
4              0                   34799.0                4.0  6.0

   Primary Energy Consumption (kWh/m2)  State of the Building
0                                190.0                    3.0
1                                402.0                    1.0
2                                563.0                    2.0
3                                181.0                    5.0
4                                 95.0                    5.0

[5 rows x 22 columns]

In [6]:
print("Shape of df", df.shape)

Shape of df (10720, 22)

In [7]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10720 entries, 0 to 10719
Data columns (total 22 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   Locality                             10720 non-null  object
 1   Zip Code                             10720 non-null  int64
 2   Type of Property                     10720 non-null  object
 3   Subtype of Property                  10720 non-null  object
 4   Price                                10720 non-null  float64
 5   Type of Sale                         10720 non-null  int64
 6   Number of Rooms                      10720 non-null  float64
 7   Livable Space (m2)                   10720 non-null  int64
 8   Fully Equipped Kitchen               10720 non-null  int64
 9   Furnished                            10720 non-null  int64
 10  Open Fire                            10720 non-null  int64
 11  Any Fireplace ?                      10720 non-null  int64
 12  Terrace                              10720 non-null  int64
 13  Terrace Area (m2)                    10720 non-null  float64
 14  Garden                               10720 non-null  int64
 15  Garden Area (m2)                     10720 non-null  float64
 16  Swimming Pool                        10720 non-null  int64
 17  Surface of the Land (m2)             10720 non-null  float64
 18  Number of Facades                    10720 non-null  float64
 19  PEB                                  10720 non-null  float64
 20  Primary Energy Consumption (kWh/m2)  10720 non-null  float64
 21  State of the Building                10720 non-null  float64
dtypes: float64(9), int64(10), object(3)
memory usage: 1.8+ MB
None

In [8]:
df.dropna(subset=['Price'], inplace=True, ignore_index=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10720 entries, 0 to 10719
Data columns (total 22 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   Locality                             10720 non-null  object
 1   Zip Code                             10720 non-null  int64
 2   Type of Property                     10720 non-null  object
 3   Subtype of Property                  10720 non-null  object
 4   Price                                10720 non-null  float64
 5   Type of Sale                         10720 non-null  int64
 6   Number of Rooms                      10720 non-null  float64
 7   Livable Space (m2)                   10720 non-null  int64
 8   Fully Equipped Kitchen               10720 non-null  int64
 9   Furnished                            10720 non-null  int64
 10  Open Fire                            10720 non-null  int64
 11  Any Fireplace ?                      10720 non-null  int64
 12  Terrace                              10720 non-null  int64
 13  Terrace Area (m2)                    10720 non-null  float64
 14  Garden                               10720 non-null  int64
 15  Garden Area (m2)                     10720 non-null  float64
 16  Swimming Pool                        10720 non-null  int64
 17  Surface of the Land (m2)             10720 non-null  float64
 18  Number of Facades                    10720 non-null  float64
 19  PEB                                  10720 non-null  float64
 20  Primary Energy Consumption (kWh/m2)  10720 non-null  float64
 21  State of the Building                9420 non-null   float64
dtypes: float64(9), int64(10), object(3)
memory usage: 1.8+ MB

In [9]:
df['Number of Fireplaces'].fillna(0, inplace=True)
df.info()

KeyError: 'Number of Fireplaces'

In [ ]:
df.head(20)

,Locality,Zip Code,Type of Property,Subtype of Property,Price,Type of Sale,Number of Rooms,Livable Space (m2),Fully Equipped Kitchen,Furnished,...,Garden,Garden Area (m2),Swimming Pool,Surface of the Land (m2),Number of Facades,Construction Year,PEB,Primary Energy Consumption (kWh/m2),State of the Building,Url
0,Ottignies-louvain-la-neuve,1348,House,exceptional-property,3790000,for-sale,6,750,0,0,...,0,0,1,160737,4,1961,E,359,To be done up,https://www.immoweb.be/en/classified/exception...
1,Anthee,5520,House,castle,550000,for-sale,2,200,1,0,...,0,0,0,110000,0,0,C,234,Good,https://www.immoweb.be/en/classified/castle/fo...
2,Dinant,5500,House,castle,550000,for-sale,2,200,1,0,...,0,0,0,110000,0,0,C,234,Good,https://www.immoweb.be/en/classified/castle/fo...
3,Namur,5000,House,castle,550000,for-sale,2,200,1,0,...,0,0,0,110000,0,0,C,234,Good,https://www.immoweb.be/en/classified/castle/fo...
4,Waasmunster,9250,House,castle,3000000,for-sale,6,967,0,0,...,0,0,1,101349,4,1810,F,708,Good,https://www.immoweb.be/en/classified/castle/fo...
5,Sprimont,4140,House,exceptional-property,6500000,for-sale,10,1500,1,0,...,0,0,1,100000,4,0,D,332,As new,https://www.immoweb.be/en/classified/exception...
6,Theux,4910,House,exceptional-property,1150000,for-sale,7,760,1,0,...,1,50000,0,100000,4,1800,D,278,Good,https://www.immoweb.be/en/classified/exception...
7,Grimbergen,1850,House,castle,2250000,for-sale,10,880,0,0,...,0,0,0,95000,4,0,E,443,To renovate,https://www.immoweb.be/en/classified/castle/fo...
8,Herne,1540,House,farmhouse,795000,for-sale,4,1745,0,0,...,0,0,0,93562,4,1850,F,1143,To renovate,https://www.immoweb.be/en/classified/farmhouse...
9,Kapellen,2950,House,villa,10500000,for-sale,11,1032,1,1,...,0,0,0,89818,4,1930,C,236,As new,https://www.immoweb.be/en/classified/villa/for...
10,Durbuy,6940,House,exceptional-property,1950000,for-sale,14,828,0,0,...,0,0,0,87810,4,0,F,499,To be done up,https://www.immoweb.be/en/classified/exception...
11,Seny,4557,House,exceptional-property,1950000,for-sale,14,828,0,0,...,0,0,0,87810,4,0,F,499,To be done up,https://www.immoweb.be/en/classified/exception...
12,Heusden,9070,House,castle,2950000,for-sale,16,875,0,0,...,0,0,0,85349,4,1881,F,596,Good,https://www.immoweb.be/en/classified/castle/fo...
13,Asse,1730,House,villa,2175000,for-sale,6,630,1,0,...,1,70470,1,70800,4,1962,E,463,Good,https://www.immoweb.be/en/classified/villa/for...
14,La-hulpe,1310,House,villa,3475000,for-sale,6,450,1,0,...,0,0,1,70000,4,1964,D,340,To be done up,https://www.immoweb.be/en/classified/villa/for...
15,Herent,3020,House,villa,1750000,for-sale,7,481,1,0,...,0,0,1,65703,0,1950,C,383,To renovate,https://www.immoweb.be/en/classified/villa/for...
16,Gembloux,5030,House,farmhouse,4500000,for-sale,7,1377,0,0,...,0,0,0,64373,4,0,C,179,As new,https://www.immoweb.be/en/classified/farmhouse...
17,Gembloux,5030,House,house,4500000,for-sale,7,1200,1,0,...,0,0,1,64300,4,1900,C,179,Good,https://www.immoweb.be/en/classified/house/for...
18,Chastre,1450,House,house,4500000,for-sale,7,1200,1,0,...,0,0,1,64300,4,1900,C,179,Good,https://www.immoweb.be/en/classified/house/for...
19,Kalmthout,2920,House,exceptional-property,10500000,for-sale,8,2139,0,0,...,0,0,1,63713,4,1997,B,106,Good,https://www.immoweb.be/en/classified/exception...

In [ ]:
df.describe()

,Zip Code,Price,Number of Rooms,Livable Space (m2),Fully Equipped Kitchen,Furnished,Open Fire,Number of Fireplaces,Terrace,Terrace Area (m2),Garden,Garden Area (m2),Swimming Pool,Surface of the Land (m2),Number of Facades,Construction Year,Primary Energy Consumption (kWh/m2)
count,9988.000000,9.988000e+03,9988.000000,9988.000000,9988.000000,9988.000000,9988.000000,9988.000000,9988.000000,9988.000000,9988.000000,9988.000000,9988.000000,9988.000000,9988.000000,9988.000000,9988.000000
mean,4704.528134,7.230441e+05,3.575991,240.214157,0.616139,0.035142,0.093512,0.204545,0.422307,15.089708,0.310072,324.933120,0.076892,1423.056167,2.318983,1556.876452,293.042151
std,3251.400818,8.276449e+05,2.006381,196.825524,0.486349,0.184148,0.291163,10.011274,0.493952,63.382652,0.462546,1668.868903,0.266434,5459.955987,1.464705,798.391151,1419.563680
min,1000.000000,2.750000e+04,1.000000,13.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,1650.000000,2.750000e+05,2.000000,110.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000,1890.000000,141.000000
50%,3380.000000,4.950000e+05,3.000000,198.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,240.000000,2.000000,1961.000000,224.000000
75%,8400.000000,8.300000e+05,4.000000,306.000000,1.000000,0.000000,0.000000,0.000000,1.000000,16.000000,1.000000,66.000000,0.000000,1000.000000,4.000000,1991.000000,335.000000
max,9992.000000,1.050000e+07,40.000000,4000.000000,1.000000,1.000000,1.000000,1000.000000,1.000000,3749.000000,1.000000,70470.000000,1.000000,160737.000000,9.000000,2026.000000,100000.000000

In [ ]:
df.groupby('Zip Code')['Price'].describe()

,count,mean,std,min,25%,50%,75%,max
Zip Code,,,,,,,,
1000,234.0,8.452821e+05,9.589733e+05,125000.0,325000.0,457500.0,975000.0,5459000.0
1020,56.0,5.366786e+05,2.636323e+05,169000.0,298000.0,524500.0,723250.0,1150000.0
1030,133.0,5.830677e+05,3.794195e+05,137500.0,320000.0,549000.0,699000.0,3300000.0
1040,81.0,9.105432e+05,6.329176e+05,145000.0,350000.0,849000.0,1295000.0,3100000.0
1050,279.0,1.399354e+06,1.273615e+06,150000.0,475000.0,1050000.0,1757500.0,8500000.0
...,...,...,...,...,...,...,...,...
9982,1.0,5.500000e+05,NaN,550000.0,550000.0,550000.0,550000.0,550000.0
9988,1.0,5.990000e+05,NaN,599000.0,599000.0,599000.0,599000.0,599000.0
9990,16.0,6.018438e+05,2.842961e+05,235000.0,366500.0,617250.0,795000.0,1165000.0
9991,9.0,5.382222e+05,3.235930e+05,295000.0,299000.0,415000.0,679000.0,1285000.0
9992,4.0,1.297250e+06,5.802071e+05,849000.0,1033500.0,1095000.0,1358750.0,2150000.0

In [ ]:
#Count the number of unique values, two ways are possible
df['Locality'].value_counts().count()
df['Locality'].nunique()

1330

In [ ]:
df['Zip Code'].value_counts().count()
df['Zip Code'].nunique()

828

In [ ]:
#Count duplicates for the same properties that have different URL.
df.duplicated(subset=df.columns.difference(['Url'])).value_counts()

False    9988
True      138
Name: count, dtype: int64

In [ ]:
#Remove duplicates for the same properties that have different URL.
df.drop_duplicates(subset=df.columns.difference(['Url']), inplace=True)

In [ ]:
df.shape

(9988, 23)

In [ ]:
# Create the new 'Open Fire' column based on 'Number of Fireplaces (0 for 0 fireplaces and 1 for more than 1 fireplaces)
df['Open Fire'] = df['Number of Fireplaces'].apply(lambda x: 0 if x == 0 else 1)

In [ ]:
df.shape

(9988, 24)

In [ ]:
df.head()

,Locality,Zip Code,Type of Property,Subtype of Property,Price,Type of Sale,Number of Rooms,Livable Space (m2),Fully Equipped Kitchen,Furnished,...,Garden Area (m2),Swimming Pool,Surface of the Land (m2),Number of Facades,Construction Year,PEB,Primary Energy Consumption (kWh/m2),State of the Building,Url,Open Fire
0,Ottignies-louvain-la-neuve,1348,House,exceptional-property,3790000,for-sale,6,750,0,0,...,0,1,160737,4,1961,E,359,To be done up,https://www.immoweb.be/en/classified/exception...,0
1,Anthee,5520,House,castle,550000,for-sale,2,200,1,0,...,0,0,110000,0,0,C,234,Good,https://www.immoweb.be/en/classified/castle/fo...,1
2,Dinant,5500,House,castle,550000,for-sale,2,200,1,0,...,0,0,110000,0,0,C,234,Good,https://www.immoweb.be/en/classified/castle/fo...,1
3,Namur,5000,House,castle,550000,for-sale,2,200,1,0,...,0,0,110000,0,0,C,234,Good,https://www.immoweb.be/en/classified/castle/fo...,1
4,Waasmunster,9250,House,castle,3000000,for-sale,6,967,0,0,...,0,1,101349,4,1810,F,708,Good,https://www.immoweb.be/en/classified/castle/fo...,1

In [ ]:
# Find the index of the current 'Number of Fireplaces' column
fireplaces_index = df.columns.get_loc('Number of Fireplaces')

In [ ]:
#Insert the new 'Open Fire' column at the same index
df.insert(fireplaces_index, 'Open Fire', df.pop('Open Fire'))

In [ ]:
df.shape

(9988, 24)

In [ ]:
df.head()

,Locality,Zip Code,Type of Property,Subtype of Property,Price,Type of Sale,Number of Rooms,Livable Space (m2),Fully Equipped Kitchen,Furnished,...,Garden,Garden Area (m2),Swimming Pool,Surface of the Land (m2),Number of Facades,Construction Year,PEB,Primary Energy Consumption (kWh/m2),State of the Building,Url
0,Ottignies-louvain-la-neuve,1348,House,exceptional-property,3790000,for-sale,6,750,0,0,...,0,0,1,160737,4,1961,E,359,To be done up,https://www.immoweb.be/en/classified/exception...
1,Anthee,5520,House,castle,550000,for-sale,2,200,1,0,...,0,0,0,110000,0,0,C,234,Good,https://www.immoweb.be/en/classified/castle/fo...
2,Dinant,5500,House,castle,550000,for-sale,2,200,1,0,...,0,0,0,110000,0,0,C,234,Good,https://www.immoweb.be/en/classified/castle/fo...
3,Namur,5000,House,castle,550000,for-sale,2,200,1,0,...,0,0,0,110000,0,0,C,234,Good,https://www.immoweb.be/en/classified/castle/fo...
4,Waasmunster,9250,House,castle,3000000,for-sale,6,967,0,0,...,0,0,1,101349,4,1810,F,708,Good,https://www.immoweb.be/en/classified/castle/fo...

In [ ]:
df.columns

Index(['Locality', 'Zip Code', 'Type of Property', 'Subtype of Property',
       'Price', 'Type of Sale', 'Number of Rooms', 'Livable Space (m2)',
       'Fully Equipped Kitchen', 'Furnished', 'Open Fire',
       'Number of Fireplaces', 'Terrace', 'Terrace Area (m2)', 'Garden',
       'Garden Area (m2)', 'Swimming Pool', 'Surface of the Land (m2)',
       'Number of Facades', 'Construction Year', 'PEB',
       'Primary Energy Consumption (kWh/m2)', 'State of the Building', 'Url'],
      dtype='object')

In [ ]:
#Rename a name of column "Open Fire" for "Number of Fireplaces"
df.rename(columns={'Open Fire': 'Number of Fireplaces'})

,Locality,Zip Code,Type of Property,Subtype of Property,Price,Type of Sale,Number of Rooms,Livable Space (m2),Fully Equipped Kitchen,Furnished,...,Garden,Garden Area (m2),Swimming Pool,Surface of the Land (m2),Number of Facades,Construction Year,PEB,Primary Energy Consumption (kWh/m2),State of the Building,Url
0,Ottignies-louvain-la-neuve,1348,House,exceptional-property,3790000,for-sale,6,750,0,0,...,0,0,1,160737,4,1961,E,359,To be done up,https://www.immoweb.be/en/classified/exception...
1,Anthee,5520,House,castle,550000,for-sale,2,200,1,0,...,0,0,0,110000,0,0,C,234,Good,https://www.immoweb.be/en/classified/castle/fo...
2,Dinant,5500,House,castle,550000,for-sale,2,200,1,0,...,0,0,0,110000,0,0,C,234,Good,https://www.immoweb.be/en/classified/castle/fo...
3,Namur,5000,House,castle,550000,for-sale,2,200,1,0,...,0,0,0,110000,0,0,C,234,Good,https://www.immoweb.be/en/classified/castle/fo...
4,Waasmunster,9250,House,castle,3000000,for-sale,6,967,0,0,...,0,0,1,101349,4,1810,F,708,Good,https://www.immoweb.be/en/classified/castle/fo...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10120,Leuven,3000,Apartment,kot,193000,for-sale,1,20,1,1,...,0,0,0,0,0,2017,A,0,As new,https://www.immoweb.be/en/classified/kot/for-s...
10121,Leuven,3000,Apartment,kot,195000,for-sale,1,18,1,1,...,0,0,0,0,0,2017,A,0,As new,https://www.immoweb.be/en/classified/kot/for-s...
10122,Blankenberge,8370,Apartment,apartment,549900,for-sale,3,225,0,0,...,0,0,0,0,0,2024,A,0,As new,https://www.immoweb.be/en/classified/apartment...
10124,Mechelen,2800,House,house,840860,for-sale,4,237,0,0,...,0,0,0,0,0,0,A,0,As new,https://www.immoweb.be/en/classified/house/for...
10125,Mechelen,2800,Apartment,apartment,289879,for-sale,1,69,0,0,...,0,0,0,0,0,0,A,0,As new,https://www.immoweb.be/en/classified/apartment...

In [ ]:
df.columns

Index(['Locality', 'Zip Code', 'Type of Property', 'Subtype of Property',
       'Price', 'Type of Sale', 'Number of Rooms', 'Livable Space (m2)',
       'Fully Equipped Kitchen', 'Furnished', 'Open Fire',
       'Number of Fireplaces', 'Terrace', 'Terrace Area (m2)', 'Garden',
       'Garden Area (m2)', 'Swimming Pool', 'Surface of the Land (m2)',
       'Number of Facades', 'Construction Year', 'PEB',
       'Primary Energy Consumption (kWh/m2)', 'State of the Building', 'Url'],
      dtype='object')

In [ ]:
# Replace 'Number of facades' with 1 where 'Type of Property' is 0 (apartment) and 'Number of facades' is 0
df.loc[(df['Type of Property'] == 0) & (df['Number of Facades'] == 0), 'Number of Facades'] = 1

# Replace 'Number of Facades' with 2 where 'Subtype of Property' is 'duplex' or 'town-house' and 'Number of Facades' is 0
df.loc[(df['Subtype of Property'].isin(['duplex', 'town-house'])) & (df['Number of Facades'] == 0), 'Number of Facades'] = 2

# Replace 'Number of Facades' with 4 where 'Type of Property' is 1 (House) and 'Number of Facades' is 0
df.loc[(df['Type of Property'] == 1) & (df['Number of Facades'] == 0), 'Number of Facades'] = 4

In [ ]:
df['Number of Facades'].isnull

0        False
1        False
2        False
3        False
4        False
         ...
10120    False
10121    False
10122    False
10124    False
10125    False
Name: Number of Facades, Length: 9988, dtype: bool

In [ ]:
df['Number of Facades'].value_counts()

Number of Facades
2    3279
4    3116
0    2291
3    1414
1      24
6       1
9       1
Name: count, dtype: int64

In [ ]:
df.to_csv('csv_files\\v1_dataset.csv', index=False)